Organizations:
  - &IPAOrderer
      Name: OrdererIPA
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/ipa.com/msp
  - &IPAOrg
      Name: IPAOrgMSP
      ID: IPAOrgMSP
      MSPDir: crypto-config/peerOrganizations/org.ipa.com/msp
      AnchorPeers:
        - Host: peer0.org.ipa.com
          Port: 7051

Application: &ApplicationDefaults
  Organizations:

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.ipa.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations:


Profiles:
  OneOrgOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *IPAOrderer
    Consortiums:
      SampleConsortium:
        Organizations:
          - *IPAOrg

  OneOrgChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *IPAOrg
